export const ALL_BLOG_GET_SUCESS = 'ALL_BLOG_GET_SUCESS';
export const ALL_BLOG_GET_ERROR = 'ALL_BLOG_GET_ERROR';

export const BLOG_GET_SUCESS = 'BLOG_GET_SUCESS';
export const BLOG_GET_ERROR = 'BLOG_GET_ERROR';

export const BLOG_ADD_SUCESS = 'BLOG_ADD_SUCESS';
export const BLOG_ADD_ERROR = 'BLOG_ADD_ERROR';

export const BLOG_UPDATE_SUCESS = 'BLOG_UPDATE_SUCESS';
export const BLOG_UPDATE_ERROR = 'BLOG_UPDATE_ERROR';

export const BLOG_DELETE_SUCESS = 'BLOG_DELETE_SUCESS';
export const BLOG_DELETE_ERROR = 'BLOG_DELETE_ERROR';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

export const RESET_MESSAGES = 'RESET_MESSAGES';